"""
Django settings for ProyectoDjango project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8doo$940^q%!2)!jco*dm*=g67%yz!d4d8qkde7y3*ujif0vn&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #an 3f-AÑADIR LA APP DE CKEDITOR
    'ckeditor',

    #an SE AGREGA TODAS LAS APPS CREADAS, PARA QUE DJANGO LOS RECONOSCA COMO APLICACION
    'mainapp',
    'pages.apps.PagesConfig', #an 2a-AGREGAR EL NOMBRE DE LA CLASE(PagesConfig) DE admin.py PARA EFECTUAR EL CAMBIO DE NOMBRE DENTRO DEL PANEL DE ADMINISTRACION | SE AGREGA ESTO AL NOMBRE DE LA APP: .apps.PagesConfig
    'blog.apps.BlogConfig', #an 2i-AGREGAR EL NOMBRE DE LA CLASE(BlogConfig) DE admin.py PARA EFECTUAR EL CAMBIO DE NOMBRE DENTRO DEL PANEL DE ADMINISTRACION | SE AGREGA ESTO AL NOMBRE DE LA APP: .apps.BlogConfig
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ProyectoDjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                #an 2c-CARGAR EL CONTEXT PROCESSORS('NOMBRE DE LA APP.NOMBRE DEL FICHERO.NOMBRE DE LA FUNCION CREADA') CREADA EN "context_processors.py"
                'pages.context_processors.get_pages',
                #an 2B-CARGAR EL CONTEXT PROCESSORS('NOMBRE DE LA APP.NOMBRE DEL FICHERO.NOMBRE DE LA FUNCION CREADA') CREADA EN "context_processors.py"
                'blog.context_processors.get_categories',
            ],
        },
    },
]

WSGI_APPLICATION = 'ProyectoDjango.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

"""
#an CONFIGURACION DE LA BD CON SQLITE3
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
"""
#an CONFIGURACION DE LA BD CON MySQL
#r NOTA: PARA CONECTAR DJANGO CON MySQL, PRIMERO NECESITAMOS INSTALAR UN DRIVER POR CMD(pip install mysqlclient). SEGUNDO REALIZAR LA MIGRACION POR CMD DENTRO DEL "ProyectoDjango" (py manage.py migrate)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'proyectodjango',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': 3306
     }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

#r 1A-CONFIGURACION PARA LA CARPETA 'media' (CREADA DENTRO DEL PROYECTO 'ProyectoDjango'), LUEGO CODIFICAR EN urls.py
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')